name: CI - build check

on:
  pull_request:
    branches: [master]

jobs:      
  ts_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup
      
      - name: TypeScript test build
        run: pnpm run check-typings
