name: CI - ESLint check

on:
  pull_request:
    branches: [master]

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup
      
      - name: Lint check
        run: npx eslint ./src --cache
